### ISSUE TITLE
Upload package to conda

### ISSUE THREAD

**Issue by danieljfarrell** [bcb/apply_defaults#2]
I have made a [conda-build](https://docs.conda.io/projects/conda-build/en/latest/) script which can be used to upload apply_defaults to Anaconda Cloud so it can be installed with the Conda package manager.

`conda install -c danieljfarrell_teraview apply_defaults`

The script is below. Please let me know if I can assist you in upload the package to the official channel.

```yaml
{% set name = "apply_defaults"%}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/bcb/apply_defaults/archive/0.1.1.tar.gz
  sha256: b046a88e04a8fb6d95b42e03570df199fe7d3d477b4fb2bc2235b307aa3a5c3b

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://github.com/bcb/apply_defaults
  license: None
  license_family: None
  license_file: 
  summary: Helps pull configuration into a project.
  doc_url:
  dev_url: 

extra:
  recipe-maintainers:
    - bcb
```
